### ISSUE TITLE
Have you tried using PyESN instead of yours implementation

### ISSUE THREAD

**Issue by aliaryan** [erik808/ESN_Lorenz63#1]
I went through your notebook and found it to be very interesting. I was wondering if you could create another section and instead of just having your implementation you could use PyESN and tune parameters and then check the results. If you are interested in doing it then let me know.

**Comment by erik808** [comment]
Hej! Well, the goal here is to get as little features in there as possible and still predict the dynamics of Lorenz63. In this notebook I want the most minimal architecture, so if you have any suggestions in that direction that would be very welcome.
